/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { chatroomDtoSchema } from "../../modules/chat/model/dto/chatroom.dto.schema.js";
import { getMessagesForRoomRequestDtoSchema, chatMessageDtoSchema, sendChatMessageRequestDtoSchema, sendChatMessageResponseDtoSchema } from "../../modules/chat/model/dto/chatMessage.dto.schema.js";
import type { ChatRouter } from "../../modules/chat/chat.router.js";

const appRouter = t.router({
  chatRouter: t.router({
    getChatRooms: publicProcedure
      .output(z.array(chatroomDtoSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getAllMessagesForRoom: publicProcedure
      .input(getMessagesForRoomRequestDtoSchema)
      .output(z.array(chatMessageDtoSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    sendMessage: publicProcedure
      .input(sendChatMessageRequestDtoSchema)
      .output(sendChatMessageResponseDtoSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    onNewMessageSent: publicProcedure
      .input(getMessagesForRoomRequestDtoSchema)
      .subscription(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ChatRouter["onNewMessageSent"]>>)
    })
});

export type AppRouter = typeof appRouter;
